---
title: "MAFLD"
output: html_document
date: "2024-06-17"
---

```{r}
library(bibliometrix)
library(tidyverse)
library(fpp3)
library(ggrepel)
library(countrycode)
library(rnaturalearth)
library(rmapshaper)
library(CoordinateCleaner)
library(patchwork)
library(cowplot)
library(openxlsx)
library(igraph)
library(tidygraph)
library(ggraph)
library(ggtext)
```

```{r}
df_cc <- readRDS("../wos/df/df_cc")
```

```{r}
# papers from single country

df_cc %>%
  group_by(UI) %>%
  mutate(CC_n = n()) %>%
  filter(CC_n == 1) %>%
  ungroup() %>%
  distinct(UI) %>% pull(UI) %>% length()

#542
```


```{r}
# papers from multiple countries

df_cc %>%
  group_by(UI) %>%
  mutate(CC_n = n()) %>%
  filter(CC_n > 1) %>%
  ungroup() %>%
  distinct(UI) %>% pull(UI) %>% length()

#710
```

```{r}
mat_cc <- df_cc %>%
    group_by(UI) %>%
    distinct(CC) %>%
    filter(n()>1) %>%
    ungroup() %>%
    mutate(n = 1) %>%
    arrange(CC) %>%
    pivot_wider(names_from = UI, values_from = n) %>%
    column_to_rownames(var = "CC") %>%
    mutate(across(everything(), ~ replace_na(.x, 0))) %>%
    as.matrix()
```


```{r}
# function for obtaining co-occurrence matrix
full_count <- function(A){
  U <- A %*% t(A)
  diag(U) <- 0
  return(U)
}
```


```{r}
# calculate adjacency matrix
adjm_cc_full <- full_count(mat_cc)
```


```{r}
gr_cc_full <- adjm_cc_full %>% graph_from_adjacency_matrix(
                                                           mode = "undirected",
                                                           weighted = TRUE,
                                                           diag = FALSE,
                                                           add.colnames = NULL,
                                                           add.rownames = NA)
```


```{r}
# convert igraph object into tidygraph
tbl_gr_cc_full <- as_tbl_graph(gr_cc_full)
```


```{r}
# check for isolated nodes
tbl_gr_cc_full %>%
  activate(nodes) %>%
  mutate(isolated = node_is_isolated()) %>%
  as_tibble() %>%
  filter(isolated == TRUE)
```

```{r}
# remove isolated
tbl_gr_cc_full <- tbl_gr_cc_full %>%
  activate(nodes) %>%
  mutate(isolated = node_is_isolated()) %>%
  filter(isolated == FALSE)
```


```{r}
# check for nodes with zero degree
tbl_gr_cc_full %>%
  activate(nodes) %>%
  mutate(degree = centrality_degree(weights = weight)) %>%
  filter(degree == 0) %>%
  as_tibble()
# 0
```


```{r}
# remove unconnected nodes (degree = 0)
tbl_gr_cc_full <- tbl_gr_cc_full %>%
  activate(nodes) %>%
  mutate(degree = centrality_degree(weights = weight))
```

```{r}
# count the total number of publications in co-citation network
tbl_gr_cc_full %>% activate(nodes) %>% as_tibble() %>% nrow()
# 108
```

```{r}
tbl_gr_cc_full %>% activate(nodes) %>% as_tibble() %>%
  arrange(desc(degree)) %>% View()
```


```{r}
tbl_gr_cc_full %>% activate(nodes) %>% as_tibble() %>% count(name) %>% View()
```


```{r}
cc_arab <- c("Algeria", "Bahrain", "Comoros", "Djibouti", "Egypt", 
             "Iraq", "Jordan", "Kuwait","Lebanon", "Libya", 
             "Mauritania", "Morocco", "Oman", "Palestine", "Qatar",
             "Saudi Arabia", "Somalia", "Sudan", "Syria", "Tunisia",
             "UAE", "Yemen")

cc_arab_query <- paste0(cc_arab, collapse = "|")
```


```{r}
#global collaboration
tbl_gr_cc_full %>%
  as_long_data_frame() %>%
  mutate(across(c(from_name, to_name),
                ~ case_when(. == "United States" ~ "USA",
                            . == "United Kingdom" ~ "UK",
                            .default = as.character(.)))) %>%
  mutate(RL = paste(from_name, "-", to_name)) %>%
  slice_max(weight, n = 15) %>%
  ggplot(aes(weight, fct_reorder(RL, weight)))+
  geom_col(fill = "#f781bf", width = 0.6)+
  labs(x ="Number of collaborations", y = "Countries",
       tag = "c")+
  scale_x_continuous(breaks = seq(0, 150, 50), 
                   limits = c(0,150), 
                   expand = c(0,0))+
  theme_classic()+
  theme(plot.tag = element_text(size = 12,face="bold"),
        plot.title = element_markdown(size=8, colour = "black", hjust = 0.5,
                                      lineheight = 1.25),
        plot.title.position = "plot",
        axis.text = element_text(size=8, colour = "black"),
        axis.title = element_text(size = 8, face = "bold"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        plot.margin = margin(0,0.5,0,0, "cm")) 
```

```{r}
# collaboration among arabs

p_col_arab <- tbl_gr_cc_full %>%
  as_long_data_frame() %>%
  mutate(across(c(from_name, to_name),
                ~ case_when(. == "United States" ~ "USA",
                            . == "United Kingdom" ~ "UK",
                            .default = as.character(.)))) %>%
  mutate(RL = paste(from_name, "-", to_name)) %>%
  filter(str_detect(RL, cc_arab_query)) %>%
  slice_max(weight, n = 15) %>%
  ggplot(aes(weight, fct_reorder(RL, weight)))+
  geom_col(fill = "#f781bf", width = 0.6)+
  labs(x ="Number of collaborations", y = "Countries",
       tag = "C")+
  scale_x_continuous(breaks = seq(0, 150, 50), 
                   limits = c(0,150), 
                   expand = c(0,0))+
  theme_classic()+
  theme(plot.tag = element_text(size = 12,face="bold"),
        plot.title = element_markdown(size=8, colour = "black", hjust = 0.5,
                                      lineheight = 1.25),
        plot.title.position = "plot",
        axis.text = element_text(size=8, colour = "black"),
        axis.title = element_text(size = 8, face = "bold"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        plot.margin = margin(0,0.5,0,0, "cm")) 

p_col_arab
```

# community detection


```{r}
# detect communities by Leiden algorithem, optimise modularity
set.seed(15)
tbl_gr_cc_full <- tbl_gr_cc_full %>%
  mutate(group = as.character(group_leiden(weights = weight,
                                           objective_function = "modularity")))
```



```{r}
# check modularity
tbl_gr_cc_full %>%
  activate(nodes) %>%
  mutate(modularity = graph_modularity(group=as.factor(group), weights = weight)) %>% 
  pull(modularity) %>% 
  head(1)
```

```{r}
# check publication counts in each group
tbl_gr_cc_full %>%
  activate(nodes) %>%
  as_tibble() %>%
  count(group) %>%
  arrange(desc(n))
```
```{r}
set.seed(51)

p1_a <- tbl_gr_cc_full %>%
  activate(nodes) %>%
  mutate(group = as.factor(group)) %>%
  ggraph("kk") +
  geom_edge_link(width = 0.3, alpha = 0.3, colour = "gray70")+
  scale_edge_colour_manual(values =  c("#ff7f00", "#4daf4a", "#377eb8", "#e41a1c", "#984ea3"),
                           guide = "none")+
  
  geom_node_point(aes(size = degree), fill = "white", colour = "white", shape = 21, stroke = 0.6)+
  geom_node_point(aes(fill = group, size = degree), colour = "gray35", shape = 21, stroke = 0.3)+
  scale_size(range = c(1.5, 4), guide = "none")+
  scale_fill_manual(values = c("#ff7f00", "#4daf4a", "#377eb8", "#e41a1c", "#984ea3"),
                    name = "Country group")+
  scale_colour_manual(values = c("#ff7f00", "#4daf4a", "#377eb8", "#e41a1c", "#984ea3"))+
  geom_node_text(aes(label = name), repel = TRUE, size = 2.8)+
  guides(fill = guide_legend(override.aes = list(size = 2.8, alpha = 1),
                               title.position = "top"),
         colour = "none")+
#  labs(tag = "")+
  theme_void()+
  theme(legend.position = "bottom",
        plot.tag = element_text(size = 12, face="bold"),
        legend.title=element_text(size=8, face = "bold", hjust = 0.5), 
        legend.text=element_text(size = 8),
        legend.key.size = unit(0.1, 'lines'),
        plot.margin = unit(c(0,0,0,0), "mm"))
```

```{r}
# create world map
world <- ne_countries(scale = "medium", returnclass = "sf") %>%
  filter(sovereignt != "Antarctica")
```

```{r}
tbl_gr_cc_full %>% activate(nodes) %>%
  as_tibble()
```
```{r}
df_cc_com <- tbl_gr_cc_full %>% activate(nodes) %>% 
  as_tibble() %>%
  mutate(ISO3C = countrycode(name, origin = "country.name", destination = "iso3c"))
```


```{r}
colnames(world)
```


```{r}
setdiff(df_cc_com$ISO3C,  world$iso_a3 )
```

```{r}
setdiff(df_cc_com$ISO3C,  world$iso_a3_eh )
```


```{r}
world %>% filter(name_long %in% c("France", "Norway")) %>% View()
```

```{r}
world <- world %>%
  mutate(iso_a3 = case_when(name_long == "France" ~ "FRA",
                            name_long == "Norway" ~ "NOR",
                            .default = iso_a3))
```

```{r}
world <- world %>%
  left_join(df_cc_com, by = join_by(iso_a3_eh == ISO3C))
```


```{r}
p_world <- world %>%
  ggplot() +
  geom_sf(aes(fill = group), alpha = 0.7)+
  scale_fill_manual(values = c("#e41a1c",
                               "#ff7f00",
                               "#377eb8",
                               "#4daf4a",
                               "#984ea3"), na.value = "gray70")+
  labs(tag = "B")+
  theme_void()+
  theme(plot.tag = element_text(size = 12, face = "bold", colour = "black"),
      #  plot.title = element_text(size = 8, face = "bold", colour = "black"),
        legend.position = "none",
        plot.margin=unit(c(0,0,0,0),"cm"),  )

p_world
```

#heb

```{r}
# rename group name based on group productivity
tbl_gr_cc_full  <- tbl_gr_cc_full   %>%
  activate(nodes) %>%
  mutate(group = case_when(group == "1" ~ "A",
                           group == "2" ~ "B",
                           group == "3" ~ "C",
                           group == "4" ~ "D",
                           group == "5" ~ "E"))
```

```{r}
num_group <- tbl_gr_cc_full %>% distinct(group) %>% pull(group) %>% length()

num_group
```

```{r}
# create for annotating groups
cc_group <- tbl_gr_cc_full %>%
  activate(nodes) %>%
  as_tibble() %>%
  mutate(iso_a3 = countrycode(name, origin = "country.name", destination = "iso3c")) %>%
  mutate(id = row_number()) %>%
  select(id, name, iso_a3, group) 
```

```{r}
# hierachial edge bundling for country co-occurrence network
# The code is adapted from the The R Graph Gallery
# https://r-graph-gallery.com/hierarchical-edge-bundling.html

# edges is a data frame organised in hierarchical structure
# from: origin -> to: group 1-5
# from: group 1-5 -> to: each country

c1_d1 <- data.frame(from = "origin", to = paste0("group", LETTERS[1:num_group]))

c1_d2 <- tbl_gr_cc_full %>% 
  activate(nodes) %>%
  as_tibble() %>%
  select(group, name) %>% 
  mutate(group = paste0("group", group)) %>%
  rename(from = "group", to = "name") %>%
  arrange(from)

c1_edges <- rbind(c1_d1, c1_d2)
```

```{r}
# leaves is a vector containing all countries ("nodes" in usual graph)

all_leaves <- tbl_gr_cc_full %>% 
  activate(nodes) %>%
  as_tibble() %>%
  pull(name)
```

```{r}
# connection is a data frame of country - country connection with weights ("edges" in usual network)

c1_connect <- gr_cc_full %>% 
  as_long_data_frame() %>%
  select(from_name, to_name, weight)
```

```{r}
# vertices is a data frame of one column describing all links passing origin, group 1-5, and countries
# value can be number of publications
c1_vertices  <-  data.frame(name = unique(c(as.character(c1_edges$from), as.character(c1_edges$to))))

c1_vertices$group <- c1_edges$from[ match(c1_vertices$name, c1_edges$to ) ]
```

```{r}
#create edge_group for coloring with edge_bundle_com2
c1_vertices <- c1_vertices %>% 
  mutate(edge_group = case_when(str_detect(name, "group") ~ name, 
                                str_detect(group, "group") ~ group,
                                .default = NA))
```

```{r}
# Information for the node includes angle, horizontal adjustment, and potential flip
# calculate the angle of the labels

c1_vertices$id <- NA
c1_leaves <- which(is.na(match(c1_vertices$name, c1_edges$from)))
nleaves <- length(c1_leaves)
c1_vertices$id[ c1_leaves ] <- seq(1:nleaves)
c1_vertices$angle <- 90 - 360 * c1_vertices$id / nleaves
 
# calculate the alignment of labels: right or left
c1_vertices$hjust <- ifelse(c1_vertices$angle < -90, 1, 0)
 
# flip angle BY to make them readable
c1_vertices$angle <- ifelse(c1_vertices$angle < -90, c1_vertices$angle+180, c1_vertices$angle)
```

```{r}
c1_vertices %>% View()
```


```{r}
# flip the label for Algeria, Croatia, Egypt
c1_vertices <- c1_vertices %>%
  mutate(angle = case_when(name == "Sudan" ~ -90-360/nleaves*1,
                           name == "Tanzania" ~ -90-360/nleaves*2,
                           name == "Uganda" ~ -90-360/nleaves*3,
                           name == "Vietnam" ~ -90-360/nleaves*4,
                           name == "Zimbabwe" ~ -90-360/nleaves*5,
                           .default = as.numeric(angle))) %>%
  mutate(hjust = case_when(name %in% c("Sudan",
                                       "Tanzania",
                                       "Uganda",
                                      "Vietnam",
                                       "Zimbabwe") ~ 0,
                 .default = as.numeric(hjust)))
```

```{r}
c1_vertices %>% View()
```


```{r}
# Create an igraph object
heb_c1 <- graph_from_data_frame( c1_edges, vertices= c1_vertices )
```

```{r}
# the connection object must refer to the ids of the leaves
# create index of vertices
c1_vertices <- c1_vertices %>% mutate(index = row_number())
```

```{r}
# 
c1_connect <- c1_connect %>%
  left_join(c1_vertices %>% select(name, index),  by = join_by(from_name == name)) %>%
  rename(from_index = "index") %>%
  left_join(c1_vertices %>% select(name, index), by = join_by(to_name == name)) %>%
  rename(to_index = "index")
```

```{r}
# c1_d2 contains country - group relationship
c1_connect <- c1_connect %>%
  left_join(c1_d2 %>% rename(group = "from", name = "to"), by = join_by(from_name == name)) %>%
  rename(from_group = "group") %>%
  left_join(c1_d2 %>% rename(group = "from", name = "to"), by = join_by(to_name == name)) %>%
  rename(to_group = "group")
```

```{r}
# convert igraph object to tidygraph and modify country names for visualisation
tbl_heb_c1 <- heb_c1 %>%
  as_tbl_graph() %>%
  activate(nodes) %>%
  left_join(tbl_gr_cc_full %>%
              activate(nodes) %>%
              select(name, degree) %>%
              as_tibble(), by = join_by(name == name)) %>%
  mutate(name = case_when(name == "Palestinian Territories" ~ "Palestine",
                          name == "United States" ~ "USA",
                          name == "United Kingdom" ~ "UK",
                          #name == "United Arab Emirates" ~ "UAE",
                          .default = as.character(name)))
```


```{r}
# plot country co-occurrence network with hierarchical edge bundling (Fig 7a)
p_country_heb <- tbl_heb_c1 %>%
  ggraph(layout = 'dendrogram', circular = TRUE) + 
  geom_node_point(aes(filter = leaf, x = x*1.05, y=y*1.05, fill = group, size = degree),
                  colour = "gray30", shape = 21, stroke = 0.3)+
  scale_fill_manual(values = c("#e41a1c",
                               "#ff7f00",
                               
                               "#377eb8",
                               "#4daf4a",
                               "#984ea3"),
                    name = "Country group",
                    labels = LETTERS[1:5],
                    guide = guide_legend(override.aes = list(size = 2.8)))+
  scale_size(range = c(1.5, 3),
             guide = "none")+
  geom_conn_bundle2(data = get_con(from = c1_connect$from_index,
                                  to = c1_connect$to_index),
                   aes(color = edge_group),
                   alpha = 0.1,
                   width = 0.3,
                   tension = 0.8,
                   lineend = "round",
                   show.legend = FALSE,
                    n = 50) +
  scale_edge_colour_manual(values = c("#e41a1c",
                               "#ff7f00",
                               "#377eb8",
                               "#4daf4a",
                               "#984ea3"),
                           na.value = "#999999")+
  geom_node_text(aes(x = x*1.1, y=y*1.1, filter = leaf, label=name, angle = angle, hjust=hjust),
                 size=2.8,
                 alpha=1) +
  coord_fixed() +
  expand_limits(x = c(-1.5, 1.5), y = c(-1.5, 1.5))+
    guides(fill = guide_legend(override.aes = list(size = 2.8, alpha = 1),
                               title.position = "top"),
         colour = "none")+
  labs(tag = "A")+
  theme_void() +
  theme(plot.tag = element_text(size = 12, face = "bold", colour = "black"),
        plot.margin=unit(c(0,0,10,0),"mm"),
        legend.title = element_text(size = 8, face = "bold", colour = "black", hjust = 0.5),
        legend.text = element_text(size = 8, colour = "black"),
        legend.direction = "horizontal",
        legend.position = "bottom")

```

```{r}
#heb_legend <- get_legend(p_country_heb)
```


```{r}
#p_country_heb_no_leg <- p_country_heb + theme(legend.position = "none")
```

```{r}
#p_world_leg <- wrap_plots(p_world, heb_legend, nrow = 2)

#p_world_leg
```

```{r}
p_row2 <- wrap_plots(p_world, p_col_arab, ncol = 2, widths = c(5,2))

p_row2
```


```{r}
p <- free(p_country_heb) +
  p_row2+
  plot_layout(nrow = 2, heights = c(4.5, 2))

ggsave("../figure/Fig6.pdf",
       p, 
       width = 175, height = 235, unit = "mm")
```

