---
title: "MAFLD"
output: html_document
date: "2024-06-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(bibliometrix)
library(tidyverse)
library(ggtext)
library(glue)
library(patchwork)
library(cowplot)
```




```{r}
# create flow chart for literature search and selection
s1 <- tibble(x= 0:100, y= 0:100)  %>% 
  ggplot(aes(x, y)) +
  scale_x_continuous(minor_breaks = seq(0, 100, 10)) +
  scale_y_continuous(minor_breaks = seq(0, 100, 10)) +
  theme_linedraw()
```

```{r}
# create boxes for literature databases

# left wos #ccebc5
# middle pubmed #fddaec
# right scopus '#fed9a6'

s1 <- s1 +
  geom_rect(xmin = 35, xmax=60, ymin = 96, ymax=100, color='black', fill='#ccebc5', size=0.3) +
  annotate('text', x = 36, y = 98,
           label= 'Records identified from Web of Science\n(n = 2252)',
           size=2.8, hjust = 0, vjust = 0.5)
```

```{r}
# add first exclusion boxes
s1 <- s1 +
  geom_rect(xmin = 45, xmax = 74, ymin = 72, ymax = 94, color='black', fill='white', size=0.3) +
    geom_segment(x = 40, xend = 44.5, y = 84, yend = 84, size=0.3, linejoin = "mitre", lineend = "butt",
    arrow = arrow(length = unit(1.5, "mm"), type= "closed"))
```

```{r}
# text for removed text
# disase term 844
# year 6
# Language 5
# Pub type 145

s1 <- s1 + annotate('text', x = 46, y = 83,
           label= "Records excluded (n = 1000):\n   No term for NAFLD/MAFLD/MASLD (n = 844)\n   Publication year 2025 (n = 6)\n   Not English (n = 5);\n      French (n = 4)\n      Spanish (n = 1)\n   Ineligible record type (n = 145);\n      Meeting Abstract (n = 135)\n      Proceedings Paper (n = 2)\n      Correction (n = 7)\n      Retracted Publication (n = 1)",
           size = 2.8, hjust = 0, vjust = 0.5)
```

```{r}
s1 <- s1 +
  geom_segment(x = 40, xend = 40, y = 96, yend = 70.5, size=0.3, linejoin = "mitre", lineend = "butt",
    arrow = arrow(length = unit(1.5, "mm"), type= "closed"))
```


```{r}
s1 <- s1 +
  geom_rect(xmin = 35, xmax = 60, ymin = 66, ymax = 70, color='black', fill='#fddaec', size=0.3) +
  annotate('text', x = 36, y = 68,
           label= 'Eligible records for analysis\n(n = 1252)',
           size=2.8, hjust = 0, vjust = 0.5)
```


# pdf

```{r}
#scale_x_continuous(expand = c(0, 0), limits = c(34, 79)) + 

s1 <- s1 +
 scale_x_continuous(expand = c(0, 0), limits = c(19, 94)) + 
  scale_y_continuous(expand = c(0, 0), limits = c(65, 101))+
  labs(tag = "A")+
  theme_void()+
  theme(plot.tag = element_text(size = 12, face = "bold", colour = "black"))

#ggsave("../figure/flow_chart.pdf", s1, width = 100, height = 75, units = "mm")
```
```{r}
p_count_year <- readRDS("../plot/p_count_year")
```

```{r}
p1 <- free(s1) +
  p_count_year+
  plot_layout(design = "
  AAAA
  BBBB")

ggsave("../figure/Fig1.pdf", p1, width = 175, height = 175, unit = "mm")
```

